#!/usr/bin/env perl

use strict;
use warnings;
use FindBin::libs;
use Patcher;

Patcher->run();

__END__
=pod

=head1 NAME patcher

=head1 SYNOPSIS

patcher [--host=localhost] [--user=www] [--db=my_db] [--install] [--plugin=NAP::DC] patch_dir

=head1 OPTIONS

=head2 --install

=head2 --host

Defaults to localhost

=head2 --user

Defaults to www

=head2 --database

=head2 --retry

For patches that have failed retry

=head2 --plugin

=head2 --search_path


=head1

=cut
